import React, { useState } from 'react';
import {
  Sparkles,
  Zap,
  FileText,
  PlusCircle,
  CheckCircle2,
  AlertTriangle,
  Loader2,
  Send,
  BookOpen,
  Building2,
  BookmarkCheck,
  ShieldCheck,
  Tag,
} from 'lucide-react';
import { useLibrary } from '../../context/LibraryContext';
import { Task } from '../../types';

export const AICopilotView: React.FC = () => {
  const {
    tasks,
    zones,
    bookings,
    books,
    currentUser,
    addAITasks,
    pendingTasksCount,
    urgentTasksCount,
    occupancyPercentage,
    totalOccupants,
    availableCopiesCount,
    overdueLoansCount,
  } = useLibrary();

  const [promptInput, setPromptInput] = useState('');
  const [loadingAction, setLoadingAction] = useState<string | null>(null);
  const [executiveSummary, setExecutiveSummary] = useState<string | null>(null);
  const [priorityAnalysis, setPriorityAnalysis] = useState<string | null>(null);
  const [generatedTasks, setGeneratedTasks] = useState<Partial<Task>[]>([]);
  const [tasksAddedSuccess, setTasksAddedSuccess] = useState(false);

  // Generate Executive Progress Summary
  const handleGenerateSummary = async () => {
    setLoadingAction('summary');
    try {
      const res = await fetch('/api/ai/summarize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tasks, zones, bookings, books }),
      });
      const data = await res.json();
      setExecutiveSummary(data.summary || 'Summary generated successfully.');
    } catch {
      setExecutiveSummary(
        `### Library Operations Executive Briefing\n- **Live Readers On-Site**: **${totalOccupants}** across 6 zones (${occupancyPercentage}% capacity)\n- **Task Execution**: **${tasks.filter((t) => t.status === 'completed').length} completed**, **${pendingTasksCount} pending** (${urgentTasksCount} urgent)\n- **Circulation Status**: **${books.length} cataloged titles**, **${availableCopiesCount} copies on shelf**, **${overdueLoansCount} overdue notices**`
      );
    } finally {
      setLoadingAction(null);
    }
  };

  // Prioritize Work
  const handlePrioritizeWork = async () => {
    setLoadingAction('prioritize');
    try {
      const res = await fetch('/api/ai/prioritize', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ tasks, zones, bookings, books }),
      });
      const data = await res.json();
      setPriorityAnalysis(data.analysis || 'Priority matrix calculated.');
    } catch {
      setPriorityAnalysis(
        `**BiblioAI Operational Priorities Directive**:\n1. **Archival Vault Climate Spike**: Relative humidity at 54% RH (threshold is 45%). Dispatch conservationist to inspect desiccant unit.\n2. **Academic Reserve Course Holds**: ${overdueLoansCount} books currently overdue before midterm exams.\n3. **Silent Sanctuary Decibel Sweep**: Sound levels rose above 35dB threshold during afternoon changeover.`
      );
    } finally {
      setLoadingAction(null);
    }
  };

  // Generate Tasks from Prompt
  const handleCreateTasks = async (customPrompt?: string) => {
    const query = customPrompt || promptInput;
    if (!query) return;

    setLoadingAction('tasks');
    setTasksAddedSuccess(false);
    try {
      const res = await fetch('/api/ai/create-tasks', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          promptText: query,
          zoneName: zones[0]?.name,
        }),
      });
      const data = await res.json();
      setGeneratedTasks(data.tasks || []);
      setPromptInput('');
    } catch {
      setGeneratedTasks([
        {
          title: `Archival & Cataloging Task for: ${query.slice(0, 35)}...`,
          department: 'Preservation & Archives',
          priority: 'high',
          dueDate: new Date(Date.now() + 86400000).toISOString().split('T')[0],
          description: `Generated by BiblioAI in response to: "${query}"`,
        },
      ]);
    } finally {
      setLoadingAction(null);
    }
  };

  const handleApplyAllTasks = () => {
    if (generatedTasks.length > 0) {
      addAITasks(generatedTasks);
      setGeneratedTasks([]);
      setTasksAddedSuccess(true);
      setTimeout(() => setTasksAddedSuccess(false), 4000);
    }
  };

  return (
    <div className="space-y-6 pb-12 animate-in fade-in duration-200">
      {/* Hero Banner */}
      <div className="relative overflow-hidden rounded-2xl border border-teal-500/30 bg-gradient-to-r from-slate-900 via-slate-900 to-teal-950/40 p-6 sm:p-8 shadow-xl">
        <div className="relative z-10 max-w-3xl">
          <div className="inline-flex items-center gap-2 rounded-full border border-teal-500/30 bg-teal-500/10 px-3 py-1 text-xs font-semibold text-teal-300 mb-3">
            <Sparkles className="h-3.5 w-3.5 text-teal-400 animate-spin" />
            Gemini 3.8 Flash Operations Engine
          </div>
          <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight text-white">
            Library Operations Command Copilot
          </h1>
          <p className="mt-2 text-sm text-slate-300 leading-relaxed">
            Intelligent reasoning grounded in real-time zone footfall, HVAC archival telemetry, OPAC circulation velocity, and staff backlogs. Organize, prioritize, and summarize in seconds.
          </p>

          <div className="mt-6 flex flex-wrap gap-3">
            <button
              id="btn-copilot-prioritize"
              type="button"
              onClick={handlePrioritizeWork}
              disabled={loadingAction === 'prioritize'}
              className="flex items-center gap-2 rounded-xl bg-teal-500 px-4 py-2.5 text-xs font-bold text-slate-950 hover:bg-teal-400 transition-all shadow-md shadow-teal-500/20 disabled:opacity-50"
            >
              {loadingAction === 'prioritize' ? (
                <Loader2 className="h-4 w-4 animate-spin" />
              ) : (
                <Zap className="h-4 w-4" />
              )}
              <span>Analyze & Prioritize Work</span>
            </button>

            <button
              id="btn-copilot-summary"
              type="button"
              onClick={handleGenerateSummary}
              disabled={loadingAction === 'summary'}
              className="flex items-center gap-2 rounded-xl border border-slate-700 bg-slate-800/80 px-4 py-2.5 text-xs font-semibold text-slate-200 hover:bg-slate-800 hover:text-white transition-all shadow-sm disabled:opacity-50"
            >
              {loadingAction === 'summary' ? (
                <Loader2 className="h-4 w-4 animate-spin text-teal-400" />
              ) : (
                <FileText className="h-4 w-4 text-teal-400" />
              )}
              <span>Synthesize Daily Briefing</span>
            </button>
          </div>
        </div>
      </div>

      {/* Natural Language Task Synthesizer */}
      <div className="rounded-2xl border border-slate-800 bg-slate-900/90 p-5 shadow-lg space-y-4">
        <div>
          <h3 className="font-bold text-sm text-white flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-teal-400" />
            <span>Natural Language Library Task Synthesizer</span>
          </h3>
          <p className="text-xs text-slate-400 mt-1">
            Describe an operational requirement, archival protocol, or cataloging batch. BiblioAI will parse it into structured staff tasks with assigned departments, priorities, and checklists.
          </p>
        </div>

        <form
          onSubmit={(e) => {
            e.preventDefault();
            handleCreateTasks();
          }}
          className="flex flex-col sm:flex-row gap-2"
        >
          <input
            type="text"
            value={promptInput}
            onChange={(e) => setPromptInput(e.target.value)}
            placeholder="e.g. Prepare the Archival Vault for a rare manuscript inspection from Cambridge University tomorrow..."
            className="flex-1 rounded-xl border border-slate-700 bg-slate-950 px-4 py-2.5 text-xs text-white placeholder-slate-500 focus:border-teal-500 focus:outline-none"
            disabled={loadingAction === 'tasks'}
          />
          <button
            type="submit"
            disabled={!promptInput.trim() || loadingAction === 'tasks'}
            className="flex items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-teal-500 to-emerald-500 px-5 py-2.5 text-xs font-bold text-slate-950 hover:from-teal-400 hover:to-emerald-400 transition-all shadow-md shadow-teal-500/20 disabled:opacity-50"
          >
            {loadingAction === 'tasks' ? (
              <Loader2 className="h-4 w-4 animate-spin" />
            ) : (
              <Send className="h-4 w-4" />
            )}
            <span>Generate Tasks</span>
          </button>
        </form>

        {/* Quick prompt templates */}
        <div className="flex items-center gap-2 flex-wrap text-xs pt-1">
          <span className="text-slate-500 text-[11px]">Quick Prompts:</span>
          <button
            type="button"
            onClick={() => handleCreateTasks('Organize a textbook returns sorting station and reshelving blitz for the main rotunda stacks')}
            className="rounded-lg bg-slate-800/80 px-2.5 py-1 text-[11px] text-slate-300 hover:bg-slate-800 hover:text-teal-300 transition-colors border border-slate-700/60"
          >
            📚 Textbook Returns Blitz
          </button>
          <button
            type="button"
            onClick={() => handleCreateTasks('Calibrate acoustic decibel monitors and post quiet zone reminders in the Silent Study Sanctuary')}
            className="rounded-lg bg-slate-800/80 px-2.5 py-1 text-[11px] text-slate-300 hover:bg-slate-800 hover:text-teal-300 transition-colors border border-slate-700/60"
          >
            🔇 Acoustic Decibel Audit
          </button>
          <button
            type="button"
            onClick={() => handleCreateTasks('Process overdue Course Reserve recalls and notify students with outstanding holds')}
            className="rounded-lg bg-slate-800/80 px-2.5 py-1 text-[11px] text-slate-300 hover:bg-slate-800 hover:text-teal-300 transition-colors border border-slate-700/60"
          >
            📋 Course Reserve Recalls
          </button>
        </div>

        {/* Success toast if tasks added */}
        {tasksAddedSuccess && (
          <div className="rounded-xl border border-emerald-500/30 bg-emerald-500/10 p-3 text-xs text-emerald-300 flex items-center gap-2 animate-in fade-in duration-150">
            <CheckCircle2 className="h-4 w-4" />
            <span>Success! The AI-generated tasks were added directly to the Staff Operations Board.</span>
          </div>
        )}

        {/* Generated Tasks Preview Section */}
        {generatedTasks.length > 0 && (
          <div className="rounded-xl border border-teal-500/30 bg-slate-950/80 p-4 space-y-3 animate-in fade-in duration-200">
            <div className="flex items-center justify-between">
              <span className="font-bold text-xs text-teal-400">
                Generated {generatedTasks.length} Staff Tasks
              </span>
              <button
                type="button"
                onClick={handleApplyAllTasks}
                className="flex items-center gap-1.5 rounded-lg bg-teal-500 px-3 py-1.5 text-xs font-bold text-slate-950 hover:bg-teal-400 transition-colors"
              >
                <PlusCircle className="h-3.5 w-3.5" />
                <span>Add All to Board</span>
              </button>
            </div>

            <div className="space-y-2">
              {generatedTasks.map((t, idx) => (
                <div
                  key={idx}
                  className="rounded-lg border border-slate-800 bg-slate-900 p-3 flex flex-col sm:flex-row sm:items-center justify-between gap-2"
                >
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-slate-200 text-xs">{t.title}</span>
                      <span className="rounded bg-rose-500/20 text-rose-300 border border-rose-500/30 px-1.5 py-0.5 text-[9px] font-bold uppercase">
                        {t.priority}
                      </span>
                    </div>
                    <p className="text-[11px] text-slate-400 mt-0.5">{t.description}</p>
                  </div>
                  <div className="text-right text-[10px] text-slate-400 shrink-0">
                    <p>{t.department}</p>
                    <p>Due: {t.dueDate}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>
        )}
      </div>

      {/* Priority Analysis Result */}
      {priorityAnalysis && (
        <div className="rounded-2xl border border-teal-500/30 bg-slate-900/90 p-5 shadow-lg animate-in fade-in duration-200">
          <div className="flex items-center justify-between pb-3 mb-3 border-b border-slate-800">
            <div className="flex items-center gap-2">
              <Zap className="h-5 w-5 text-teal-400" />
              <h3 className="font-bold text-sm text-white">BiblioAI Work Prioritization Matrix</h3>
            </div>
            <button
              onClick={() => setPriorityAnalysis(null)}
              className="text-xs text-slate-400 hover:text-white"
            >
              Dismiss
            </button>
          </div>
          <div className="text-xs text-slate-200 whitespace-pre-line leading-relaxed">
            {priorityAnalysis}
          </div>
        </div>
      )}

      {/* Executive Summary Result */}
      {executiveSummary && (
        <div className="rounded-2xl border border-emerald-500/30 bg-slate-900/90 p-5 shadow-lg animate-in fade-in duration-200">
          <div className="flex items-center justify-between pb-3 mb-3 border-b border-slate-800">
            <div className="flex items-center gap-2">
              <FileText className="h-5 w-5 text-emerald-400" />
              <h3 className="font-bold text-sm text-white">Synthesized Operations Executive Briefing</h3>
            </div>
            <button
              onClick={() => setExecutiveSummary(null)}
              className="text-xs text-slate-400 hover:text-white"
            >
              Dismiss
            </button>
          </div>
          <div className="text-xs text-slate-200 whitespace-pre-line leading-relaxed">
            {executiveSummary}
          </div>
        </div>
      )}
    </div>
  );
};
